# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentshield" do
  name "agentshield"
  desc "Runtime security gateway and compliance scanner for LLM agents"
  homepage "https://github.com/AI-AgentLens/AI_Agent_Shield"
  version "0.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentshield"

  on_macos do
    on_intel do
      url "https://github.com/AI-AgentLens/AI_Agent_Shield/releases/download/v#{version}/agentshield_#{version}_darwin_amd64.tar.gz"
      sha256 "de60152e7a5d63b69cfc08c85dffa2740df89d0b8128a102f6ba2ef0198dbc80"
    end
    on_arm do
      url "https://github.com/AI-AgentLens/AI_Agent_Shield/releases/download/v#{version}/agentshield_#{version}_darwin_arm64.tar.gz"
      sha256 "8d9effb4261cddfdcb2b0f7944af12cda41c9563e32cb9c647c6335d01c8c286"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AI-AgentLens/AI_Agent_Shield/releases/download/v#{version}/agentshield_#{version}_linux_amd64.tar.gz"
      sha256 "c354756f33c5e24c7b3a1be6d970a92d6379dbe315ac2a174c7c1deceb2ecb6c"
    end
    on_arm do
      url "https://github.com/AI-AgentLens/AI_Agent_Shield/releases/download/v#{version}/agentshield_#{version}_linux_arm64.tar.gz"
      sha256 "e0a2729061f167dc5f4446a0c4c669e2138f07df068b857af7920a08c8d4391e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentshield"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentcompliance"]
    end
  end

  caveats do
    "Two tools installed:"
    "  agentshield      — Runtime security gateway for AI agents"
    "  agentcompliance  — Local compliance scanner (semgrep-based)"
    ""
    "Quick start:"
    "  agentshield setup"
    "  agentshield login"
  end

  # No zap stanza required
end
